# R/RcppExports.R

# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Calculate Blackjack Score (C++)
#' @description
#' Fast C++ implementation for calculating blackjack hand scores.
#' Used internally for performance, but also available for direct use.
#' @param ranks Character vector of card ranks (e.g., c("A", "10", "K")).
#' @return Integer: the blackjack score for the given hand.
#' @examples
#' calculate_score_cpp(c("A", "10"))   # 21 (Blackjack)
#' calculate_score_cpp(c("10", "7", "4")) # 21
#' calculate_score_cpp(c("A", "A", "9"))  # 21 (A as 11, other as 1)
#' @export
calculate_score_cpp <- function(ranks) {
    .Call('_wombat21_calculate_score_cpp', PACKAGE = 'wombat21', ranks)
}

