# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate Blackjack Score (C++)
#'
#' Fast C++ implementation for calculating blackjack hand scores
#' @name calculate_score_cpp
#' @param ranks Character vector of card ranks (e.g., c("A", "10", "K"))
#' @return Integer score of the hand
#' @export
calculate_score_cpp <- function(ranks) {
    .Call('_wombat21_calculate_score_cpp', PACKAGE = 'wombat21', ranks)
}

